version: "3.8"
services:
  web:
    build: ./app
    image: 542180722535.dkr.ecr.us-west-1.amazonaws.com/django_docker_aws
    command: 700972041082.dkr.ecr.us-west-1.amazonaws.com/workshop2
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    image: 542180722535.dkr.ecr.us-west-1.amazonaws.com/django_docker_aws
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:


